use_frameworks!

platform :ios, '10.0'

target 'LSImageCompression_Example' do
  pod 'LSImageCompression', :path => '../'

  target 'LSImageCompression_Tests' do
    inherit! :search_paths

    
  end
end
